### ISSUE TITLE
GetEnvironmentVariable failed to get the latest environment variable

### ISSUE THREAD

**Issue by lonelyparasol** [delphidabbler/article-demos#3]
Please forgive me for asking the question here. I can't find the right place to express this question.
There are changes in the registry, this function can not get the changes, even if the program is closed and restarted, the computer must restart or task manager restart to read.
Is there any way to trigger it to update, or any other way to get the latest environment variables?
Using TRegistry to read the registry directly will only get the original string. Paths like "%Path%" are not converted.

**Comment by delphidabbler** [comment]
I guess Windows must only read the environment variables from the registry under the conditions you describe, because _GetEnvironmentVariable_ ultimately calls the Windows API, and so the API must not be able to see the changed environment variable. Because this is an API level problem I can't see a way to fix it I'm afraid. If anyone knows better please leave a comment.

With regard to variables containing `%%` delimited text, like `%Path%`, _GetEnvironmentVariable_ doesn't convert the string by design, just in case the user actually wants the unconverted string. What you need is _ExpandEnvVars_ from the same unit. This does what you want. In the case of environment variables that don't contain any `%% `delimiters, _ExpandEnvVars_ acts exactly like _GetEnvironmentVariable_, so there's no need to check for `%%` delimited text before calling it.

Hope that helps.

**Comment by delphidabbler** [comment]
BTW there's a fully documented and tested version of this demo code in my [DDabLib](https://github.com/delphidabbler/ddablib) project - see the [PJEnvVars unit](https://github.com/delphidabbler/ddablib/tree/main/projects/envvars).

**Comment by lonelyparasol** [comment]
Thanks for your help, ExpandEnvironmentStrings can help me parse %Path%

**Comment by delphidabbler** [comment]
👍
